In [107]:
# create timestamp
import datetime as dt

print(f"Notebook last run (end-to-end): {dt.datetime.now()}")

Notebook last run (end-to-end): 2023-06-25 19:49:44.072570


In [108]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [109]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [110]:
scalar.ndim

0

In [111]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [112]:
vector.ndim

1

In [113]:
matrix = tf.constant([[10,7],[2,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>

In [114]:
matrix.ndim

2

In [115]:
another_matrix = tf.constant([[10,7],[3,2],[8,9]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [116]:
tensor = tf.constant(
    [[[1,2,3],[4,5,6],[7,8,9]],
     [[10,11,12],[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [117]:
tensor.ndim

3

In [118]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [119]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [120]:
# unchangeable_tensor[0].assign(7)

In [121]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Check are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [122]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(12)
random_2 = random_2.normal(shape=(3,2))

# Check are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [123]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
# This is how shuffle work
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [124]:
tf.random.shuffle(not_shuffled, seed=32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [125]:
# Set the seed Global random seed
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [126]:
# Set the seed Global random seed
# If its comment, it will be shuffle randomly
# tf.random.set_seed(42)

tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [127]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [128]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [129]:
# Turn Numpy array into tensor
import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)
A = tf.constant(numpy_A, shape=(2,4,3))
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [130]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [131]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [132]:
print("Datatypes of every element : ", rank_4_tensor.dtype)
print("Number of dimensions (rank) : ", rank_4_tensor.ndim)
print("Elements along axis 0 of tensor : ", rank_4_tensor.shape[0])
print("Elements along lasat axis of tensor : ", rank_4_tensor.shape[1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatypes of every element :  <dtype: 'float32'>
Number of dimensions (rank) :  4
Elements along axis 0 of tensor :  2
Elements along lasat axis of tensor :  3
Total number of elements (2*3*4*5): 120


In [133]:
# get the first 2 items of each  dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [134]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [135]:
rank_2_tensor = tf.constant([[10,7],[3,4]])

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [136]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [137]:
# Or you can use this
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [138]:
# Manipulating Tensor

In [139]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [140]:
tensor -10, tensor * 10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>)

In [141]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [142]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [143]:
tf.multiply(tensor, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]], dtype=int32)>

In [144]:
# Matrix Multiplication

print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [145]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [146]:
x = tf.constant([[1,2],[3,4],[5,6]])
y = tf.constant([[7,8],[9,10],[11,12]])

# x@y

In [147]:
z = tf.reshape(y, shape=(2,3))

In [148]:
x @ z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [149]:
tf.transpose(x), x

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [150]:
X = tf.transpose(x)
tf.matmul(X, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [151]:
# Dot product
tf.tensordot(X,y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [152]:
# Matrix multiplication

In [153]:
X, x,y
Y = tf.transpose(y)
Y,x

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [154]:
tf.matmul(x,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [155]:
# check shape of y, reshaped y, and transpose y
y.shape, tf.reshape(y,(2,3)).shape, tf.transpose(y)

(TensorShape([3, 2]),
 TensorShape([2, 3]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

In [156]:
# Checking Value of y, reshape y, and transpose y

print("Normal y : ", y)
print("reshape y to 2,3 : ", tf.reshape(y, (2,3)))
print("Transpose y : ", tf.transpose(y))

Normal y :  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
reshape y to 2,3 :  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Transpose y :  tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [157]:
# this is dtype float32
B = tf.constant([1.7, 7.4])
# change to int32
C = tf.constant([1,7])
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [158]:
B = tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [159]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [160]:
# Getting the absolute Value
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [161]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [162]:
# Finding the min max
E = tf.constant(np.random.randint(low=0,high=100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96, 18, 62,  7, 30, 47, 77, 66, 36,  4, 38, 73,  0, 18, 79,  7, 86,
       94, 37, 56, 17, 71, 38, 35, 43, 97, 63, 30, 82, 17,  0, 20,  1, 45,
       15, 18, 23, 46, 74, 46, 51, 26, 22, 22, 97,  7, 50, 26, 29,  3])>

In [163]:
# Get the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [164]:
# Get the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [165]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [166]:
# get the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2045>

In [167]:
# get the std deviation
E = tf.cast(E, dtype=tf.float32)
tf.math.reduce_variance(E), tf.math.reduce_std(E), tf.math.reduce_min(E)

(<tf.Tensor: shape=(), dtype=float32, numpy=814.05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=28.53156>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>)

In [168]:
# Finding the position of max and min
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.97249603, 0.97023109, 0.07382417, 0.28860609, 0.91046964,
       0.63910766, 0.73650972, 0.4878486 , 0.85346526, 0.24529091,
       0.88618369, 0.70903475, 0.9890212 , 0.52442567, 0.64440996,
       0.5609311 , 0.27518426, 0.11280448, 0.56151799, 0.41744264,
       0.64622608, 0.24317688, 0.61166537, 0.44285466, 0.80256569,
       0.6224307 , 0.7078227 , 0.29531541, 0.97678348, 0.76317419,
       0.71193706, 0.14570014, 0.71656924, 0.04714431, 0.90154576,
       0.62659026, 0.97725766, 0.5172901 , 0.36088132, 0.19669826,
       0.93442504, 0.04510808, 0.31550136, 0.01771986, 0.97177523,
       0.19548727, 0.87064125, 0.75913573, 0.16274416, 0.08737087])>

In [169]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [170]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [171]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 12
The maximum value of F is: 0.9890211979278015
Using tf.argmax() to index F, the maximum value of F is: 0.9890211979278015
Are the two max values the same (they should be)? True


In [172]:
# Squeezing the tensor
G = tf.constant(np.random.randint(0,100,50), shape=(1,1,1,1,50))
G , G.shape, G.ndim

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
 array([[[[[21, 58, 73, 44,  9, 14, 99, 55, 60, 82, 42, 97, 21, 88, 69,
            53, 79, 70, 46, 26,  9, 65, 13, 64, 32, 39, 22, 42, 94, 35,
            90,  8, 50, 42, 31, 22, 34, 73, 83, 37, 82, 43, 55, 86, 67,
            11, 14, 83, 22, 46]]]]])>,
 TensorShape([1, 1, 1, 1, 50]),
 5)

In [173]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape, G_squeezed.ndim

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([21, 58, 73, 44,  9, 14, 99, 55, 60, 82, 42, 97, 21, 88, 69, 53, 79,
        70, 46, 26,  9, 65, 13, 64, 32, 39, 22, 42, 94, 35, 90,  8, 50, 42,
        31, 22, 34, 73, 83, 37, 82, 43, 55, 86, 67, 11, 14, 83, 22, 46])>,
 TensorShape([50]),
 1)

In [174]:
G_reshape = tf.reshape(G, shape=(1,5,5,2))
G_reshape_squeezed = tf.squeeze(G_reshape)

G_reshape_squeezed,G_reshape_squeezed.shape,G_reshape_squeezed.ndim,

(<tf.Tensor: shape=(5, 5, 2), dtype=int64, numpy=
 array([[[21, 58],
         [73, 44],
         [ 9, 14],
         [99, 55],
         [60, 82]],
 
        [[42, 97],
         [21, 88],
         [69, 53],
         [79, 70],
         [46, 26]],
 
        [[ 9, 65],
         [13, 64],
         [32, 39],
         [22, 42],
         [94, 35]],
 
        [[90,  8],
         [50, 42],
         [31, 22],
         [34, 73],
         [83, 37]],
 
        [[82, 43],
         [55, 86],
         [67, 11],
         [14, 83],
         [22, 46]]])>,
 TensorShape([5, 5, 2]),
 3)

In [175]:
#  One hot encoding

In [178]:
some_list = [0,1,2,3]
tf.one_hot(some_list,depth=2)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [180]:
tf.one_hot(some_list, depth=4, on_value="masook", off_value="keluar")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'masook', b'keluar', b'keluar', b'keluar'],
       [b'keluar', b'masook', b'keluar', b'keluar'],
       [b'keluar', b'keluar', b'masook', b'keluar'],
       [b'keluar', b'keluar', b'keluar', b'masook']], dtype=object)>

In [182]:
# squaring, root, square root
H = tf.constant(np.arange(10))
H

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [183]:
tf.square(H)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [185]:
H_cast = tf.cast(H, dtype=tf.float16)
tf.sqrt(H_cast)

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828,
       3.   ], dtype=float16)>

In [186]:
tf.math.log(H_cast)

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([  -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 ,
       2.08  , 2.197 ], dtype=float16)>

In [188]:
# Manipulating tf.Variable
I = tf.Variable(np.arange(1,10))
I

<tf.Variable 'Variable:0' shape=(9,) dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [192]:
I.assign([10,11,12,13,14,15,16,17,18])
I

<tf.Variable 'Variable:0' shape=(9,) dtype=int64, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18])>

In [193]:
I

<tf.Variable 'Variable:0' shape=(9,) dtype=int64, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18])>

In [194]:
I.assign_add([4,4,4,4,4,4,4,4,4,])
I

<tf.Variable 'Variable:0' shape=(9,) dtype=int64, numpy=array([14, 15, 16, 17, 18, 19, 20, 21, 22])>

In [195]:
# Tensors and Numpy
J = tf.constant(np.array([3.,7.,9.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 7., 9.])>

In [196]:
np.array(J), type(np.array(J))

(array([3., 7., 9.]), numpy.ndarray)

In [197]:
J.numpy()

array([3., 7., 9.])

In [198]:
numpy_J = tf.constant(np.array([3.,7.,9.]))
tensor_J = tf.constant([3.,7.,9.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [199]:
# Using @tf.function

In [202]:
def function(x,y):
  return x**2+y

x = tf.constant(np.arange(0,10))
y = tf.constant(np.arange(10,20))
function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [203]:
@tf.function
def tf_function(x,y):
  return x ** 2 +y
tf_function(x,y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [204]:
print(tf.config.list_physical_devices('GPU'))

[]


In [205]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))



[]


In [206]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found
